import "./globals.css";
import "../styles/global.css";
import { Inter } from "next/font/google";
import ProgressBar from "@badrap/bar-of-progress";
const inter = Inter({ subsets: ["latin"] });
const progress = new ProgressBar({
  size: 4,
  color: "#FE595E",
  className: "z-10",
  delay: 100,
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
